"""The compact binary dependency representations, generated once and carried along.

A certificate in this demonstration publishes its dependency structure twice: as METAS
UncLib XML, and as the compact binary form the same library writes for results with too
many input quantities to spell out. The XML is a documented format that
:mod:`vcqi.domain.linprop` reproduces byte for byte. The binary form is an undocumented
layout that only UncLib itself produces.

Reverse-engineering it would be the wrong move twice over: it is fragile, and it is a
poor way to treat a licensed library whose format is not published. So the blobs are
generated on a machine that has UncLib installed and committed here as data. Results
computed with the software are data; the licence restricts distributing the software.

Each blob is keyed by a digest of the XML representation of the same result. That makes
the key content-derived, so a blob cannot silently attach itself to a result it does not
describe: change the measurement and the key changes with it, the lookup misses, and the
certificate says the binary form is unavailable rather than publishing a stale one.

Regenerate with::

    uv sync --extra unclib
    uv run python -m vcqi.domain.unclib_blobs

which rebuilds the world, records every blob UncLib produces, and rewrites
``unclib_blobs.json``. The file is checked by ``tests/test_linprop_equivalence.py``.
"""

from __future__ import annotations

import base64
import hashlib
import json
from functools import lru_cache
from pathlib import Path
from typing import Final

__all__ = ["blob_key", "blob_for", "BLOBS_PATH", "UNAVAILABLE_NOTE"]

#: Where the committed blobs live. Inside the package, so a wheel carries them.
BLOBS_PATH: Final[Path] = Path(__file__).parent / "unclib_blobs.json"

#: Recorded on a credential in place of the binary representation when no blob is
#: available, which happens for a result the committed set does not cover.
UNAVAILABLE_NOTE: Final[str] = (
    "The compact binary form is written only by METAS UncLib itself, which this "
    "deployment does not carry. The XML representation above states the same "
    "dependency structure."
)


def blob_key(unclib_xml: str) -> str:
    """Derive the key under which a result's binary form is stored.

    The XML is byte-identical whichever engine produced it, so the key does not depend
    on how the demonstrator was run.

    Args:
        unclib_xml: The XML dependency representation of the result.

    Returns:
        A hex digest, truncated to something readable in a diff.
    """
    return hashlib.sha256(unclib_xml.encode("utf-8")).hexdigest()[:32]


@lru_cache(maxsize=1)
def _blobs() -> dict[str, bytes]:
    """Load and decode the committed blobs.

    Returns:
        Every stored blob by key, or an empty mapping when the file is absent.
    """
    if not BLOBS_PATH.is_file():
        return {}
    stored = json.loads(BLOBS_PATH.read_text(encoding="utf-8"))
    return {key: base64.b64decode(value) for key, value in stored["blobs"].items()}


def blob_for(unclib_xml: str) -> bytes | None:
    """Return the binary representation of the result this XML describes.

    Args:
        unclib_xml: The XML dependency representation of the result.

    Returns:
        The bytes UncLib wrote for that result, or None when no blob was recorded for
        it. A caller should omit the representation rather than substitute anything.
    """
    return _blobs().get(blob_key(unclib_xml))


def _write(blobs: dict[str, bytes]) -> None:
    """Write the blob file, sorted so that regenerating it produces a clean diff.

    Args:
        blobs: Every blob to store, by key.
    """
    payload = {
        "note": (
            "Generated by 'python -m vcqi.domain.unclib_blobs' on a machine with METAS "
            "UncLib installed. Keyed by a digest of each result's XML representation. "
            "See unclib_blobs.py."
        ),
        "blobs": {
            key: base64.b64encode(blobs[key]).decode("ascii") for key in sorted(blobs)
        },
    }
    BLOBS_PATH.write_text(
        json.dumps(payload, indent=2, sort_keys=False) + "\n",
        encoding="utf-8",
        newline="\n",
    )


def main() -> None:
    """Rebuild the world with UncLib and record every binary representation it writes.

    Raises:
        SystemExit: If this process is not computing with METAS UncLib, since the
            pure-Python engine cannot produce these bytes and would write nothing.
    """
    from vcqi.domain.engine import unclib_available
    from vcqi.domain.uncertainty import to_unclib_xml

    if not unclib_available():
        raise SystemExit(
            "this needs METAS UncLib: run 'uv sync --extra unclib' first, and do not "
            "set VCQI_ENGINE=linprop"
        )

    from vcqi.actors import scenarios
    from vcqi.domain import uncertainty

    collected: dict[str, bytes] = {}
    requests = 0

    # Capture at the one place a binary representation is produced, so the set recorded
    # is exactly the set the credentials ask for and nothing is guessed about which
    # results those are.
    real_binary = uncertainty._unclib_binary_from_library

    def record(result: object) -> bytes:
        nonlocal requests
        blob = real_binary(result)
        collected[blob_key(to_unclib_xml(result))] = blob  # type: ignore[arg-type]
        requests += 1
        return blob

    uncertainty._unclib_binary_from_library = record  # type: ignore[assignment]
    try:
        scenarios.build_world()
    finally:
        uncertainty._unclib_binary_from_library = real_binary  # type: ignore[assignment]

    _write(collected)
    print(f"recorded {len(collected)} blobs from {requests} requests -> {BLOBS_PATH}")


if __name__ == "__main__":
    main()
